# Generated by Django 4.0.4 on 2022-05-14 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='Равна ли С сумме A и B?', max_length=256)),
                ('a', models.IntegerField(default=0)),
                ('b', models.IntegerField(default=0)),
                ('c', models.IntegerField(default=0)),
                ('pub_date', models.DateField(default=datetime.date(2022, 5, 14))),
            ],
        ),
    ]
