# Generated by Django 4.0.4 on 2022-05-14 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_abc_options_alter_abc_a_alter_abc_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='a',
            field=models.IntegerField(default=0, verbose_name='A1'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='b',
            field=models.IntegerField(default=0, verbose_name='B1'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='c',
            field=models.IntegerField(default=0, verbose_name='C1'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 15, 49, 5, 551108, tzinfo=utc), verbose_name='Дата1'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='task',
            field=models.CharField(default='Равна ли С сумме A и B?', max_length=256, verbose_name='Задание1'),
        ),
    ]
