# Generated by Django 4.0.4 on 2022-05-14 16:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_abc_a_alter_abc_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='a',
            field=models.IntegerField(default=0, verbose_name='A1'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 16, 19, 9, 397268, tzinfo=utc), verbose_name='Дата1'),
        ),
    ]
