# Generated by Django 4.0.4 on 2022-05-18 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_abc_a_alter_abc_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 12, 11, 52, 557764, tzinfo=utc), verbose_name='Дата1'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='task',
            field=models.CharField(blank='True', default='Равна ли С сумме A и B?', max_length=256, verbose_name='Заданиe2'),
        ),
    ]
