# Generated by Django 4.0.4 on 2022-05-18 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_abc_pub_date_alter_abc_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='a',
            field=models.IntegerField(default=0, verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='b',
            field=models.IntegerField(default=0, verbose_name='B'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='c',
            field=models.IntegerField(default=0, verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 12, 20, 35, 232125, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='task',
            field=models.CharField(blank='False', default='Равна ли С сумме A и B?', max_length=256, verbose_name='Содержание задания'),
        ),
    ]
