# Generated by Django 4.0.4 on 2022-05-18 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_abc_a_alter_abc_b_alter_abc_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 12, 23, 52, 42713, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='task',
            field=models.CharField(default='Равна ли С сумме A и B?', max_length=256, verbose_name='Содержание задания'),
        ),
    ]
