# Generated by Django 4.0.4 on 2022-05-18 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_abc_id_alter_abc_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Первичный'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 14, 26, 1, 180558, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
