# Generated by Django 4.0.4 on 2022-05-18 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_abc_id_alter_abc_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abc',
            options={'verbose_name': 'Таблица выполненных заданий', 'verbose_name_plural': 'Таблицы выполненных заданий'},
        ),
        migrations.AlterField(
            model_name='abc',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 16, 37, 47, 374631, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
