# Generated by Django 4.0.4 on 2022-05-18 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_abc_options_alter_abc_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Первичный ключ'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 16, 55, 25, 787899, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='task',
            field=models.CharField(default='Равна ли С сумме A и B?', max_length=256, verbose_name='Содержание задания'),
        ),
    ]
